In [24]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from api_import import *

In [25]:
df = pd.read_json("../data/census_data.json")
df.set_index(['COUNTY_ID', 'TRACT_ID'],inplace=True,drop=True)
df.head(5)

                      ALAND  ALAND_SQMI   AWATER  AWATER_SQMI BOROUGH  \
COUNTY_ID TRACT_ID
5         100       1672467       0.646  1032658        0.399   Bronx
          200        455322       0.176   926899        0.358   Bronx
          400        912391       0.352   602945        0.233   Bronx
          1600       485079       0.187        0        0.000   Bronx
          1900      1656134       0.639  1139660        0.440   Bronx

                    FRAC_LAND        GEOID   INTPTLAT  INTPTLONG     LATMAX  \
COUNTY_ID TRACT_ID
5         100        0.618259  36005000100  40.793492 -73.883532  40.800898
          200        0.329413  36005000200  40.803486 -73.860438  40.808779
          400        0.602105  36005000400  40.808915 -73.850488  40.814458
          1600       1.000000  36005001600  40.818848 -73.858076  40.821984
          1900       0.592366  36005001900  40.800999 -73.909373  40.808528

                      ...      pop_mexican  pop_native  pop_pacific  \
COUNTY_ID TRACT_ID    ...
5         100         ...              312           0            0
          200         ...              120          35            0
          400         ...              139           0            0
          1600        ...               83           0            0
          1900        ...              525           0            0

                   pop_polish  pop_portuguese pop_puertorican  pop_russian  \
COUNTY_ID TRACT_ID
5         100              29               7            1831           39
          200               0               0            1618            0
          400              21               0            2416            0
          1600              0               0            1878            0
          1900              5               0             547            3

                    pop_total  pop_vietnamese  pop_white
COUNTY_ID TRACT_ID
5         100            9191               0       1361
          200            4858               0       1352
          400            5344               0       1339
          1600           5215               0       1535
          1900           2562               0        995

[5 rows x 67 columns]

In [26]:
ziplist = df.ZIPCODE.astype(str).unique()
ziplist

array(['11370', '10473', '10455', '10454', '10472', '10453', '10451',
       '10460', '10452', '10456', '10459', '10462', '10474', '10465', '0',
       '10457', '10461', '10458', '10468', '10475', '10463', '10469',
       '10471', '10467', '10466', '10470', '10464', '11201', '11232',
       '11220', '11205', '11217', '11209', '11231', '11219', '11215',
       '11228', '11238', '11425', '11218', '11214', '11225', '11216',
       '11204', '11206', '11221', '11233', '11223', '11213', '11224',
       '11235', '11207', '11237', '11230', '11222', '11211', '11226',
       '11229', '11234', '11236', '11210', '11203', '11212', '11239',
       '11208', '10004', '10002', '10271', '10038', '10005', '10007',
       '10009', '10279', '10278', '10013', '10003', '10014', '10012',
       '10010', '10011', '10016', '10001', '10168', '10165', '10036',
       '10017', '10022', '10174', '10177', '10110', '10199', '10018',
       '10154', '10119', '10112', '10065', '10019', '10153', '10021',
       '10075', '10162', '10028', '10128', '10023', '10069', '10029',
       '10024', '10025', '10035', '10026', '10027', '10115', '10037',
       '10031', '10039', '10030', '10032', '10044', '10033', '10040',
       '10034', '10282', '10280', '11109', '11421', '11101', '11418',
       '11416', '11106', '11417', '11414', '11103', '11102', '11420',
       '11105', '11419', '11415', '11377', '11104', '11436', '11435',
       '11378', '11424', '11432', '11451', '11433', '11434', '11373',
       '11372', '11413', '11371', '11369', '11368', '11375', '11412',
       '11423', '11427', '11428', '11379', '11429', '11385', '11411',
       '11422', '11374', '11430', '11367', '11355', '11354', '11357',
       '11356', '11697', '11694', '11693', '11692', '11691', '11360',
       '11359', '11358', '11361', '11365', '11366', '11364', '11362',
       '11363', '11005', '11426', '11040', '11004', '10301', '10305',
       '10304', '10310', '10306', '10308', '10312', '10314', '10303',
       '10309'], dtype=object)

In [27]:
zillow_data = query_zillow(ziplist)

zipcode =  11370
zipcode =  10473
zipcode =  10455
zipcode =  10454
zipcode =  10472
zipcode =  10453
zipcode =  10451
zipcode =  10460
zipcode =  10452
zipcode =  10456
zipcode =  10459
zipcode =  10462
zipcode =  10474
zipcode =  10465
zipcode =  10457
zipcode =  10461
zipcode =  10458
zipcode =  10468
zipcode =  10475
zipcode =  10463
zipcode =  10469
zipcode =  10471
zipcode =  10467
zipcode =  10466
zipcode =  10470
zipcode =  10464
zipcode =  11201
zipcode =  11232
zipcode =  11220
zipcode =  11205
zipcode =  11217
zipcode =  11209
zipcode =  11231
zipcode =  11219
zipcode =  11215
zipcode =  11228
zipcode =  11238
zipcode =  11425
zipcode =  11218
zipcode =  11214
zipcode =  11225
zipcode =  11216
zipcode =  11204
zipcode =  11206
zipcode =  11221
zipcode =  11233
zipcode =  11223
zipcode =  11213
zipcode =  11224
zipcode =  11235
zipcode =  11207
zipcode =  11237
zipcode =  11230
zipcode =  11222
zipcode =  11211
zipcode =  11226
zipcode =  11229
zipcode =  11234
zipcode =  11236
zipcode =  11210
zipcode =  11203
zipcode =  11212
zipcode =  11239
zipcode =  11208
zipcode =  10004
zipcode =  10002
zipcode =  10271
zipcode =  10038
zipcode =  10005
zipcode =  10007
zipcode =  10009
zipcode =  10279
zipcode =  10278
zipcode =  10013
zipcode =  10003
zipcode =  10014
zipcode =  10012
zipcode =  10010
zipcode =  10011
zipcode =  10016
zipcode =  10001
zipcode =  10168
zipcode =  10165
zipcode =  10036
zipcode =  10017
zipcode =  10022
zipcode =  10174
zipcode =  10177
zipcode =  10110
zipcode =  10199
zipcode =  10018
zipcode =  10154
zipcode =  10119
zipcode =  10112
zipcode =  10065
zipcode =  10019
zipcode =  10153
zipcode =  10021
zipcode =  10075
zipcode =  10162
zipcode =  10028
zipcode =  10128
zipcode =  10023
zipcode =  10069
zipcode =  10029
zipcode =  10024
zipcode =  10025
zipcode =  10035
zipcode =  10026
zipcode =  10027
zipcode =  10115
zipcode =  10037
zipcode =  10031
zipcode =  10039
zipcode =  10030
zipcode =  10032
zipcode =  10044
zipcode =  10033
zipcode =  10040
zipcode =  10034
zipcode =  10282
zipcode =  10280
zipcode =  11109
zipcode =  11421
zipcode =  11101
zipcode =  11418
zipcode =  11416
zipcode =  11106
zipcode =  11417
zipcode =  11414
zipcode =  11103
zipcode =  11102
zipcode =  11420
zipcode =  11105
zipcode =  11419
zipcode =  11415
zipcode =  11377
zipcode =  11104
zipcode =  11436
zipcode =  11435
zipcode =  11378
zipcode =  11424
zipcode =  11432
zipcode =  11451
zipcode =  11433
zipcode =  11434
zipcode =  11373
zipcode =  11372
zipcode =  11413
zipcode =  11371
zipcode =  11369
zipcode =  11368
zipcode =  11375
zipcode =  11412
zipcode =  11423
zipcode =  11427
zipcode =  11428
zipcode =  11379
zipcode =  11429
zipcode =  11385
zipcode =  11411
zipcode =  11422
zipcode =  11374
zipcode =  11430
zipcode =  11367
zipcode =  11355
zipcode =  11354
zipcode =  11357
zipcode =  11356
zipcode =  11697
zipcode =  11694
zipcode =  11693
zipcode =  11692
zipcode =  11691
zipcode =  11360
zipcode =  11359
zipcode =  11358
zipcode =  11361
zipcode =  11365
zipcode =  11366
zipcode =  11364
zipcode =  11362
zipcode =  11363
zipcode =  11005
zipcode =  11426
zipcode =  11040
zipcode =  11004
zipcode =  10301
zipcode =  10305
zipcode =  10304
zipcode =  10310
zipcode =  10306
zipcode =  10308
zipcode =  10312
zipcode =  10314
zipcode =  10303
zipcode =  10309

In [28]:
zillow_data.items()

[('10065', [nan, 922900.0]),
 ('10069', [nan, 1650000.0]),
 ('10453', [nan, 0.0]),
 ('10452', [nan, 0.0]),
 ('10451', [nan, 0.0]),
 ('10457', [nan, 0.0]),
 ('10456', [256600.0, 0.0]),
 ('10455', [nan, 0.0]),
 ('10454', [nan, 0.0]),
 ('10459', [297800.0, 0.0]),
 ('10458', [nan, 0.0]),
 ('11232', [588100.0, 307200.0]),
 ('10010', [nan, 807700.0]),
 ('11385', [496400.0, 440300.0]),
 ('10017', [nan, 588300.0]),
 ('10016', [nan, 653200.0]),
 ('0', [nan, nan]),
 ('10014', [nan, 827000.0]),
 ('10304', [394100.0, 358500.0]),
 ('10282', [nan, 1868300.0]),
 ('10280', [787800.0, 628000.0]),
 ('10119', [nan, 0.0]),
 ('10115', [nan, 0.0]),
 ('10112', [nan, 0.0]),
 ('10110', [nan, 0.0]),
 ('11372', [448700.0, 255800.0]),
 ('11109', [nan, 0.0]),
 ('11379', [596200.0, 614200.0]),
 ('11378', [561500.0, 515000.0]),
 ('11102', [nan, 0.0]),
 ('11103', [689400.0, 471500.0]),
 ('11377', [595800.0, 241200.0]),
 ('11101', [780500.0, 859900.0]),
 ('11106', [579200.0, 354900.0]),
 ('11370', [541900.0, 325000.0]),
 ('11104', [nan, 256500.0]),
 ('10199', [nan, 0.0]),
 ('11375', [770500.0, 266900.0]),
 ('11374', [607900.0, 226100.0]),
 ('10027', [1002900.0, 566800.0]),
 ('10028', [nan, 904500.0]),
 ('10040', [nan, 448500.0]),
 ('11371', [nan, 0.0]),
 ('10029', [702600.0, 670000.0]),
 ('10044', [nan, 47445200.0]),
 ('11201', [1040900.0, 814500.0]),
 ('11203', [383700.0, 440000.0]),
 ('10128', [nan, 806200.0]),
 ('11205', [721900.0, 573300.0]),
 ('11204', [698400.0, 474000.0]),
 ('11207', [311800.0, 273000.0]),
 ('11206', [nan, 415000.0]),
 ('11209', [826300.0, 249200.0]),
 ('11208', [325800.0, 386700.0]),
 ('11105', [683500.0, 0.0]),
 ('10024', [nan, 952500.0]),
 ('10025', [1055400.0, 670100.0]),
 ('11368', [414000.0, 258200.0]),
 ('11369', [532400.0, 160800.0]),
 ('11366', [731700.0, 650000.0]),
 ('10022', [nan, 833500.0]),
 ('11364', [731500.0, 239700.0]),
 ('11365', [692600.0, 498100.0]),
 ('11362', [790100.0, 370700.0]),
 ('11363', [861600.0, 650000.0]),
 ('11360', [656400.0, 333300.0]),
 ('10023', [nan, 883700.0]),
 ('10021', [nan, 871800.0]),
 ('11212', [308700.0, 0.0]),
 ('11213', [nan, 320000.0]),
 ('11210', [604800.0, 444600.0]),
 ('11211', [916900.0, 763200.0]),
 ('11216', [773100.0, 0.0]),
 ('11217', [1012200.0, 768500.0]),
 ('11214', [569000.0, 270000.0]),
 ('11215', [941600.0, 760400.0]),
 ('10035', [nan, 0.0]),
 ('10034', [nan, 445300.0]),
 ('11218', [739800.0, 475000.0]),
 ('10036', [1229800.0, 950000.0]),
 ('10031', [634900.0, 375000.0]),
 ('10030', [569900.0, 465000.0]),
 ('10033', [nan, 426700.0]),
 ('10032', [nan, 485000.0]),
 ('11359', [nan, 0.0]),
 ('11358', [717500.0, 678400.0]),
 ('11005', [nan, 504600.0]),
 ('11004', [574000.0, 251900.0]),
 ('11697', [nan, 410000.0]),
 ('11694', [629600.0, 407300.0]),
 ('11357', [750700.0, 357600.0]),
 ('11356', [557500.0, 480000.0]),
 ('11355', [573800.0, 288900.0]),
 ('11354', [545700.0, 211000.0]),
 ('10039', [nan, 481500.0]),
 ('11451', [nan, 0.0]),
 ('10038', [nan, 842000.0]),
 ('10309', [469700.0, 421500.0]),
 ('10308', [419200.0, 311000.0]),
 ('10037', [nan, 425900.0]),
 ('10306', [409300.0, 400400.0]),
 ('10305', [384500.0, 352300.0]),
 ('11040', [548100.0, 562500.0]),
 ('10303', [287900.0, 334800.0]),
 ('10301', [424900.0, 500000.0]),
 ('11229', [550100.0, 289800.0]),
 ('11228', [747300.0, 639000.0]),
 ('10026', [nan, 906900.0]),
 ('11226', [621700.0, 450600.0]),
 ('11225', [1005800.0, 370000.0]),
 ('11224', [428900.0, 273600.0]),
 ('11223', [nan, 495000.0]),
 ('11222', [854500.0, 799000.0]),
 ('11221', [799800.0, 0.0]),
 ('11220', [606000.0, 275000.0]),
 ('11219', [nan, 452500.0]),
 ('10271', [nan, 0.0]),
 ('10168', [nan, 0.0]),
 ('11429', [396200.0, 370000.0]),
 ('11428', [424000.0, 370000.0]),
 ('11421', [410200.0, 362000.0]),
 ('11420', [398700.0, 379700.0]),
 ('11423', [446200.0, 279000.0]),
 ('11422', [385300.0, 360000.0]),
 ('11425', [nan, 0.0]),
 ('11424', [nan, 0.0]),
 ('11427', [478300.0, 451200.0]),
 ('11426', [510000.0, 440300.0]),
 ('10153', [nan, 0.0]),
 ('10154', [nan, 0.0]),
 ('10310', [396300.0, 351500.0]),
 ('10312', [432900.0, 401000.0]),
 ('10314', [404900.0, 348600.0]),
 ('11231', [953100.0, 876500.0]),
 ('10162', [nan, 0.0]),
 ('11238', [823100.0, 662700.0]),
 ('11239', [nan, 0.0]),
 ('10019', [nan, 754500.0]),
 ('10018', [nan, 660300.0]),
 ('11230', [811000.0, 301500.0]),
 ('10012', [nan, 1350300.0]),
 ('10011', [nan, 1089500.0]),
 ('11233', [nan, 0.0]),
 ('11234', [455500.0, 489500.0]),
 ('11235', [568700.0, 224700.0]),
 ('11236', [351300.0, 24000.0]),
 ('11237', [nan, 404600.0]),
 ('11693', [334400.0, 337200.0]),
 ('11432', [630900.0, 392900.0]),
 ('11433', [350300.0, 225000.0]),
 ('11430', [nan, 0.0]),
 ('11436', [337800.0, 265000.0]),
 ('11434', [353500.0, 360500.0]),
 ('11435', [400100.0, 150000.0]),
 ('10004', [1517200.0, 1015200.0]),
 ('10005', [1210900.0, 983000.0]),
 ('10007', [2636900.0, 2240000.0]),
 ('10001', [2333200.0, 110500.0]),
 ('10002', [885800.0, 581000.0]),
 ('10003', [1525100.0, 982900.0]),
 ('11692', [288400.0, 0.0]),
 ('10165', [nan, 0.0]),
 ('10009', [1104600.0, 500000.0]),
 ('10279', [nan, 0.0]),
 ('10278', [nan, 0.0]),
 ('10475', [nan, 0.0]),
 ('10474', [nan, 0.0]),
 ('10471', [788900.0, 387700.0]),
 ('10470', [nan, 0.0]),
 ('10473', [333700.0, 405600.0]),
 ('10472', [nan, 0.0]),
 ('11691', [384700.0, 415000.0]),
 ('11361', [701300.0, 502000.0]),
 ('10075', [nan, 852300.0]),
 ('10174', [nan, 0.0]),
 ('10177', [nan, 0.0]),
 ('10466', [354600.0, 417000.0]),
 ('10467', [323400.0, 212600.0]),
 ('10464', [448200.0, 0.0]),
 ('10465', [398400.0, 357300.0]),
 ('10462', [106100.0, 115000.0]),
 ('10463', [512300.0, 259800.0]),
 ('10460', [nan, 0.0]),
 ('10461', [nan, 348000.0]),
 ('10468', [nan, 0.0]),
 ('10469', [364200.0, 338000.0]),
 ('11411', [389500.0, 386000.0]),
 ('11412', [379500.0, 360000.0]),
 ('11413', [386700.0, 350000.0]),
 ('11414', [539800.0, 165000.0]),
 ('11415', [494900.0, 192900.0]),
 ('11416', [405700.0, 0.0]),
 ('11417', [409400.0, 416000.0]),
 ('11418', [456900.0, 393000.0]),
 ('11419', [396200.0, 360000.0]),
 ('10013', [3117100.0, 2806100.0]),
 ('11367', [598700.0, 193900.0]),
 ('11373', [453500.0, 240500.0])]

In [29]:
df['zillow_house_median'] = 0.0
df['zillow_house_index'] = 0.0

In [30]:
zillow_zips = zillow_data.keys()
for irow, row in df.iterrows():
    if str(row['ZIPCODE']) in zillow_zips:
        df.loc[irow,'house_index'] = zillow_data[str(row['ZIPCODE'])][0]
        df.loc[irow,'house_median'] = zillow_data[str(row['ZIPCODE'])][1]
    else:
        df.loc[irow,'house_index'] = np.nan
        df.loc[irow,'house_median'] = np.nan

In [31]:
1./(float(len(df.ZIPCODE.unique()))/len(df.house_median.unique()))

0.7222222222222222

In [32]:
print "70% of census tracts have zip-code level median house prices"

70% of census tracts have zip-code level median house prices

In [33]:
df.reset_index().to_json("../data/census_zillow_data.json",orient="records")